# Here I saw something incredible https://rakudoweekly.blog/2025/01/06/2025-01/
# We can write the string "Happy 2025!" using Happy 𝚺 (^10)»³

# Using UNICODE?
# Creating your own prefixes?

sub Happy ($_) { say "Happy $_!" }
sub prefix:<𝚺>(\x) { x.sum }

Happy 𝚺 (^10)»³

# ^10: This creates a range from 0 up to (but not including) 10. 
# In essence, it represents the numbers 0, 1, 2, 3, 4, 5, 6, 7, 8, 9.

# »³ 
    # ³ 
        # This is Raku's exponentiation operator (equivalent to ** 3 in many other languages), meaning "raised to the power of 3" (cubed).
    # » 
        # This is a hyper operator. It takes an operator (in this case, ³) and applies it element-wise to a list or array (the range generated by ^10). It essentially "lifts" the operator to work on a collection of values.

