CREATE TABLE IF NOT EXISTS BaseStat (
    EntityId INTEGER NOT NULL UNIQUE, 
    DIPLOMACY INTEGER NOT NULL,
    MARTIAL INTEGER NOT NULL,
    STEWARDSHIP INTEGER NOT NULL,
    INTRIGUE INTEGER NOT NULL,
    LEARNING INTEGER NOT NULL,
    FOREIGN KEY (EntityId) REFERENCES Entity(Id) ON DELETE CASCADE
);