CREATE TABLE IF NOT EXISTS BaseStat (
    EntityId INTEGER NOT NULL UNIQUE, 
    Diplomancy INTEGER NOT NULL,
    Martial INTEGER NOT NULL,
    Stewardship INTEGER NOT NULL,
    Intrigue INTEGER NOT NULL,
    Learning INTEGER NOT NULL,
    FOREIGN KEY (EntityId) REFERENCES Entity(Id) ON DELETE CASCADE
);