CREATE TABLE IF NOT EXISTS Position3D (
    EntityId INTEGER NOT NULL UNIQUE,
    X REAL NOT NULL,
    Y REAL NOT NULL,
    Z REAL NOT NULL,
    FOREIGN KEY (EntityId) REFERENCES Entity(Id) ON DELETE CASCADE
);